In [1]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\USER\miniconda3\envs\ai_security\python.exe
3.12.13 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:26:47) [MSC v.1942 64 bit (AMD64)]

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("../dataset/csic_database.csv")
data.head()

,Unnamed: 0,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,classification,URL
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [4]:
data.columns.tolist()

['Unnamed: 0',
 'Method',
 'User-Agent',
 'Pragma',
 'Cache-Control',
 'Accept',
 'Accept-encoding',
 'Accept-charset',
 'language',
 'host',
 'cookie',
 'content-type',
 'connection',
 'lenght',
 'content',
 'classification',
 'URL']

In [5]:
data.shape
data["Unnamed: 0"].value_counts()

Unnamed: 0
Normal       36000
Anomalous    25065
Name: count, dtype: int64

In [6]:
data["classification"].value_counts()

classification
0    36000
1    25065
Name: count, dtype: int64

In [7]:
pd.crosstab(data["Unnamed: 0"], data["classification"])

classification      0      1
Unnamed: 0
Anomalous           0  25065
Normal          36000      0

In [8]:
y = data["classification"]

In [9]:
data.dtypes

Unnamed: 0           str
Method               str
User-Agent           str
Pragma               str
Cache-Control        str
Accept               str
Accept-encoding      str
Accept-charset       str
language             str
host                 str
cookie               str
content-type         str
connection           str
lenght               str
content              str
classification     int64
URL                  str
dtype: object

In [10]:
data.isnull().sum()

Unnamed: 0             0
Method                 0
User-Agent             0
Pragma                 0
Cache-Control          0
Accept               397
Accept-encoding        0
Accept-charset         0
language               0
host                   0
cookie                 0
content-type       43088
connection             0
lenght             43088
content            43088
classification         0
URL                    0
dtype: int64

In [11]:
data = data.fillna("")

In [12]:
data["URL"].head()

0     http://localhost:8080/tienda1/index.jsp HTTP/1.1
1    http://localhost:8080/tienda1/publico/anadir.j...
2    http://localhost:8080/tienda1/publico/anadir.j...
3    http://localhost:8080/tienda1/publico/autentic...
4    http://localhost:8080/tienda1/publico/autentic...
Name: URL, dtype: str

In [13]:
data[data["classification"] == 0]["URL"].head(10)

0     http://localhost:8080/tienda1/index.jsp HTTP/1.1
1    http://localhost:8080/tienda1/publico/anadir.j...
2    http://localhost:8080/tienda1/publico/anadir.j...
3    http://localhost:8080/tienda1/publico/autentic...
4    http://localhost:8080/tienda1/publico/autentic...
5    http://localhost:8080/tienda1/publico/caracter...
6    http://localhost:8080/tienda1/publico/caracter...
7    http://localhost:8080/tienda1/publico/carrito....
8    http://localhost:8080/tienda1/publico/entrar.j...
9    http://localhost:8080/tienda1/publico/entrar.j...
Name: URL, dtype: str

In [14]:
data[data["classification"] == 1]["URL"].head(10)

36000    http://localhost:8080/tienda1/publico/anadir.j...
36001    http://localhost:8080/tienda1/publico/anadir.j...
36002    http://localhost:8080/tienda1/publico/anadir.j...
36003    http://localhost:8080/tienda1/publico/anadir.j...
36004    http://localhost:8080/asf-logo-wide.gif~ HTTP/1.1
36005    http://localhost:8080/tienda1/publico/autentic...
36006    http://localhost:8080/tienda1/publico/autentic...
36007    http://localhost:8080/tienda1/publico/autentic...
36008    http://localhost:8080/tienda1/publico/autentic...
36009    http://localhost:8080/tienda1/publico/autentic...
Name: URL, dtype: str

In [15]:
data.duplicated().sum()

np.int64(0)

In [16]:
data["classification"].value_counts(normalize=True)

classification
0    0.589536
1    0.410464
Name: proportion, dtype: float64

In [17]:
df = data.copy()

In [18]:
df = df.fillna("")
df.isnull().sum()

Unnamed: 0         0
Method             0
User-Agent         0
Pragma             0
Cache-Control      0
Accept             0
Accept-encoding    0
Accept-charset     0
language           0
host               0
cookie             0
content-type       0
connection         0
lenght             0
content            0
classification     0
URL                0
dtype: int64

In [19]:
text_columns = [
    "Method",
    "User-Agent",
    "host",
    "cookie",
    "content-type",
    "content",
    "URL"
]

df["request_text"] = df[text_columns].astype(str).agg(" ".join, axis=1)

In [20]:
df[["request_text", "classification"]].head()

                                        request_text  classification
0  GET Mozilla/5.0 (compatible; Konqueror/3.5; Li...               0
1  GET Mozilla/5.0 (compatible; Konqueror/3.5; Li...               0
2  POST Mozilla/5.0 (compatible; Konqueror/3.5; L...               0
3  GET Mozilla/5.0 (compatible; Konqueror/3.5; Li...               0
4  POST Mozilla/5.0 (compatible; Konqueror/3.5; L...               0

In [21]:
X = df["request_text"]
y = df["classification"]

In [22]:
X.head()
y.head()

0    0
1    0
2    0
3    0
4    0
Name: classification, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [24]:
print(X_train.shape)
print(X_test.shape)

(48852,)
(12213,)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    max_features=20000
)

In [26]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [27]:
X_test_tfidf = vectorizer.transform(X_test)

In [28]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(48852, 20000)
(12213, 20000)

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [30]:
y_pred = model.predict(X_test_tfidf)

In [31]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9736346516007532

In [32]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Anomalous"]
))

              precision    recall  f1-score   support

      Normal       0.96      1.00      0.98      7200
   Anomalous       1.00      0.94      0.97      5013

    accuracy                           0.97     12213
   macro avg       0.98      0.97      0.97     12213
weighted avg       0.97      0.97      0.97     12213

In [33]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[7187   13]
 [ 309 4704]]

In [34]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_tfidf, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [35]:
rf_pred = rf_model.predict(X_test_tfidf)

In [36]:
from sklearn.metrics import accuracy_score

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.9680668140506018

In [37]:
print(classification_report(
    y_test,
    rf_pred,
    target_names=["Normal", "Anomalous"]
))

              precision    recall  f1-score   support

      Normal       0.95      0.99      0.97      7200
   Anomalous       0.99      0.93      0.96      5013

    accuracy                           0.97     12213
   macro avg       0.97      0.96      0.97     12213
weighted avg       0.97      0.97      0.97     12213

In [38]:
rf_cm = confusion_matrix(y_test, rf_pred)
print(rf_cm)

[[7150   50]
 [ 340 4673]]

In [39]:
import joblib

joblib.dump(model, "../model/logistic_regression_model.pkl")
joblib.dump(vectorizer, "../model/tfidf_vectorizer.pkl")

['../model/tfidf_vectorizer.pkl']

In [40]:
import joblib

model = joblib.load("../model/logistic_regression_model.pkl")
vectorizer = joblib.load("../model/tfidf_vectorizer.pkl")

In [41]:
test_request = "GET Mozilla/5.0 localhost /tienda1/index.jsp HTTP/1.1"

test_vector = vectorizer.transform([test_request])

print(model.predict(test_vector))

[1]

In [42]:
print(model.predict_proba(test_vector))

[[0.336049 0.663951]]

In [43]:
normal_request = df[df["classification"] == 0]["request_text"].iloc[0]

print(normal_request)

GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=1F767F17239C9B670A39E9B10C3825F4   http://localhost:8080/tienda1/index.jsp HTTP/1.1

In [44]:
normal_vector = vectorizer.transform([normal_request])

print(model.predict(normal_vector))
print(model.predict_proba(normal_vector))

[0]
[[0.98756271 0.01243729]]

In [45]:
anomalous_request = df[df["classification"] == 1]["request_text"].iloc[0]

print(anomalous_request)

GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=B92A8B48B9008CD29F622A994E0F650D   http://localhost:8080/tienda1/publico/anadir.jsp?id=2&nombre=Jam%F3n+Ib%E9rico&precio=85&cantidad=%27%3B+DROP+TABLE+usuarios%3B+SELECT+*+FROM+datos+WHERE+nombre+LIKE+%27%25&B1=A%F1adir+al+carrito HTTP/1.1

In [46]:
test_request = "GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=1F767F17239C9B670A39E9B10C3825F4 http://localhost:8080/tienda1/index.jsp HTTP/1.1"

test_vector = vectorizer.transform([test_request])

print(model.predict(test_vector))
print(model.predict_proba(test_vector))

[0]
[[0.98756271 0.01243729]]

In [47]:
test_request="GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=1F767F17239C9B670A39E9B10C3825F4   http://localhost:8080/tienda1/index.jsp HTTP/1.1"
test_vector = vectorizer.transform([test_request])

print(model.predict(test_vector))
print(model.predict_proba(test_vector))

[0]
[[0.98756271 0.01243729]]

In [48]:
test_request = """GET Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0
127.0.0.1:8000
http://127.0.0.1:8000/"""

In [49]:
test_vector = vectorizer.transform([test_request])

print(model.predict(test_vector))
print(model.predict_proba(test_vector))

[1]
[[4.70006429e-04 9.99529994e-01]]

In [50]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\dataset\csic_database.csv"
)

print(df.shape)
print(df.columns.tolist())

(61065, 17)
['Unnamed: 0', 'Method', 'User-Agent', 'Pragma', 'Cache-Control', 'Accept', 'Accept-encoding', 'Accept-charset', 'language', 'host', 'cookie', 'content-type', 'connection', 'lenght', 'content', 'classification', 'URL']

In [51]:
print(df["classification"].value_counts())

classification
0    36000
1    25065
Name: count, dtype: int64

In [52]:
normal_requests = df[df["classification"] == 0]["URL"].head(10)

print(normal_requests.to_string(index=False))

  http://localhost:8080/tienda1/index.jsp HTTP/1.1
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/carrito.j...
http://localhost:8080/tienda1/publico/entrar.js...
http://localhost:8080/tienda1/publico/entrar.js...

In [53]:
anomalous_requests = df[df["classification"] == 1]["URL"].head(10)

print(anomalous_requests.to_string(index=False))

http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
 http://localhost:8080/asf-logo-wide.gif~ HTTP/1.1
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...

In [54]:
text_columns = [
    "Method",
    "User-Agent",
    "host",
    "cookie",
    "content-type",
    "content",
    "URL"
]

df["request_text"] = df[text_columns].fillna("").astype(str).agg(" ".join, axis=1)

In [55]:
print("NORMAL REQUESTS")
print(
    df[df["classification"] == 0]["request_text"]
    .head(3)
    .to_string(index=False)
)

NORMAL REQUESTS
GET Mozilla/5.0 (compatible; Konqueror/3.5; Lin...
GET Mozilla/5.0 (compatible; Konqueror/3.5; Lin...
POST Mozilla/5.0 (compatible; Konqueror/3.5; Li...

In [56]:
print("ANOMALOUS REQUESTS")
print(
    df[df["classification"] == 1]["request_text"]
    .head(3)
    .to_string(index=False)
)

ANOMALOUS REQUESTS
GET Mozilla/5.0 (compatible; Konqueror/3.5; Lin...
POST Mozilla/5.0 (compatible; Konqueror/3.5; Li...
GET Mozilla/5.0 (compatible; Konqueror/3.5; Lin...

In [57]:
normal = df[df["classification"] == 0].iloc[0]
anomalous = df[df["classification"] == 1].iloc[0]

for column in text_columns:
    print("\n---", column, "---")
    print("NORMAL:   ", normal[column])
    print("ANOMALOUS:", anomalous[column])

--- Method ---
NORMAL:    GET
ANOMALOUS: GET

--- User-Agent ---
NORMAL:    Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)
ANOMALOUS: Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)

--- host ---
NORMAL:    localhost:8080
ANOMALOUS: localhost:8080

--- cookie ---
NORMAL:    JSESSIONID=1F767F17239C9B670A39E9B10C3825F4
ANOMALOUS: JSESSIONID=B92A8B48B9008CD29F622A994E0F650D

--- content-type ---
NORMAL:    nan
ANOMALOUS: nan

--- content ---
NORMAL:    nan
ANOMALOUS: nan

--- URL ---
NORMAL:    http://localhost:8080/tienda1/index.jsp HTTP/1.1
ANOMALOUS: http://localhost:8080/tienda1/publico/anadir.jsp?id=2&nombre=Jam%F3n+Ib%E9rico&precio=85&cantidad=%27%3B+DROP+TABLE+usuarios%3B+SELECT+*+FROM+datos+WHERE+nombre+LIKE+%27%25&B1=A%F1adir+al+carrito HTTP/1.1

In [58]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import matplotlib.pyplot as plt

In [59]:
df = pd.read_csv(
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\dataset\csic_database.csv"
)

print("Dataset shape:", df.shape)
print(df.columns.tolist())

Dataset shape: (61065, 17)
['Unnamed: 0', 'Method', 'User-Agent', 'Pragma', 'Cache-Control', 'Accept', 'Accept-encoding', 'Accept-charset', 'language', 'host', 'cookie', 'content-type', 'connection', 'lenght', 'content', 'classification', 'URL']

In [60]:
text_columns = [
    "Method",
    "User-Agent",
    "host",
    "cookie",
    "content-type",
    "content",
    "URL"
]

df["request_text"] = (
    df[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

print(df["request_text"].head(3))

0    GET Mozilla/5.0 (compatible; Konqueror/3.5; Li...
1    GET Mozilla/5.0 (compatible; Konqueror/3.5; Li...
2    POST Mozilla/5.0 (compatible; Konqueror/3.5; L...
Name: request_text, dtype: str

In [61]:
print(df["classification"].value_counts())

print("\nClass meaning:")
print("0 = Normal")
print("1 = Anomalous")

classification
0    36000
1    25065
Name: count, dtype: int64

Class meaning:
0 = Normal
1 = Anomalous

In [62]:
X = df["request_text"]
y = df["classification"]

print("Number of requests:", len(X))
print("Number of labels:", len(y))

Number of requests: 61065
Number of labels: 61065

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 48852
Testing samples: 12213

In [64]:
tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (48852, 50000)
Testing TF-IDF shape: (12213, 50000)

In [65]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_tfidf, y_train)

print("Model training completed.")

Model training completed.

In [66]:
y_pred = model.predict(X_test_tfidf)

print("Predictions completed.")
print(y_pred[:20])

Predictions completed.
[1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 1 0 0 0]

In [67]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 97.63%

In [68]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision * 100:.2f}%")
print(f"Recall:    {recall * 100:.2f}%")
print(f"F1-score:  {f1 * 100:.2f}%")

Precision: 99.89%
Recall:    94.31%
F1-score:  97.02%

In [69]:
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Anomalous"]
))

              precision    recall  f1-score   support

      Normal       0.96      1.00      0.98      7200
   Anomalous       1.00      0.94      0.97      5013

    accuracy                           0.98     12213
   macro avg       0.98      0.97      0.98     12213
weighted avg       0.98      0.98      0.98     12213

In [70]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[7195    5]
 [ 285 4728]]

In [71]:
# Find anomalous requests that the model incorrectly classified as normal

missed = (y_test == 1) & (y_pred == 0)

missed_requests = X_test[missed]

print("Number of missed anomalous requests:", len(missed_requests))

print("\nFirst 10 missed requests:\n")
for i, request in enumerate(missed_requests.head(10)):
    print(f"--- Request {i+1} ---")
    print(request[:1000])
    print()

Number of missed anomalous requests: 285

First 10 missed requests:

--- Request 1 ---
GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=B4591E4D0B2EEF4D212E3C4F2AE8C250   http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=mullinix&password=portadguero&nombre=Nanda&apellidos=Santagata+Pillajo&email=wakasa%40miami-beach.gf&dni=44636251J&direccion=C%2F+Perro+De+San+Cecilio%2C+197+11%3FA&ciudad=Cerro+de+And%E9valo%2C+El&cp=19275&provincia=Guadalaja%2Fra&ntc=5604259372572557&B1=Registrar HTTP/1.1

--- Request 2 ---
POST Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=2C389F93D274BB679C2472641355B878 application/x-www-form-urlencoded modoA=registro&login=bradee&password=ran7%F3n&nombre=Jairo&apellidos=Uruburu+Ayensa&email=coffer%40soyvalenciano.bu&dni=19782082N&direccion=Pe%F1a+Dorada+87%2C+1%3FF&ciudad=Valfarta&cp=09660&provincia=Girona&ntc=1025019984542981&B1=Registrar http://localhost:8080/tienda1/miembros/editar.jsp HTTP/1.1

--- Request 3 ---
GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=148F713002A0D9F27005C3C4C17A0851   http://localhost:8080/tienda1/miembros/salir.jsp~ HTTP/1.1

--- Request 4 ---
GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=29E8C2A1AA63BD3C058ECC112E74102B   http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=de%3F-anna&pwd=j%2Baqu%E9s&remember=on&B1=Entrar HTTP/1.1

--- Request 5 ---
POST Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=B200B9B16BE526A6985694266F4666A9 application/x-www-form-urlencoded modo=entrar&login=woins%3Fky&pwd=pagaDEra&remember=off&B1=Entrar http://localhost:8080/tienda1/publico/autenticar.jsp HTTP/1.1

--- Request 6 ---
GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=979B0E0CFDA468149FF372E24E183F11   http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=attilla&password=hIe4%E1t*i29&nombre=Neyen&apellidos=Oll%E9+Verdin&email=balfour.riabinkina%40monsur.ls&dni=7A%279417AM&direccion=Calle+Iztueta%2C+105+&ciudad=Sant+Mart%ED+de+Riucorb&cp=01427&provincia=Salamanca&ntc=1701163791515432&B1=Registrar HTTP/1.1

--- Request 7 ---
GET Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=2FFB291E68DDEB3F5CD29F2CA12A59C2   http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=bredfeld0&pwd=43tete%2Cm638&remember=on&B1=Entrar HTTP/1.1

--- Request 8 ---
POST Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=EF665EF27A9AF242F85FC205D9113B14 application/x-www-form-urlencoded modo=registro&login=perez&password=interclusi%F3n&nombre=Fabrina&apellidos=Chomb%F3+Mantero&email=casini-fridley%40civicosdns.ws&dniA=34788445W&direccion=Rotonda+Palomera+Centro+4%2C+5%3FA&ciudad=Seriny%E0&cp=32755&provincia=Madrid&ntc=6682713987061411&B1=Registrar http://localhost:8080/tienda1/publico/registro.jsp HTTP/1.1

--- Request 9 ---
POST Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=993A74436453849C4CC7224DEC62F1DA application/x-www-form-urlencoded modo=registro&login=hallsy6&password=machete&nombre=Facunda&apellidos=Naudi&email=dinehart%40barebackspain.sh&dni=22586543Z&direccion=C%2F+Torreta%2C+115%2C+6A&ciudad=Taradell&cp=4416A&provincia=Valladolid&ntc=6475224906467741&B1=Registrar http://localhost:8080/tienda1/publico/registro.jsp HTTP/1.1

--- Request 10 ---
POST Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko) localhost:8080 JSESSIONID=62AA72E90E0A408614E662C7180E1ADA application/x-www-form-urlencoded modo=registro&login=biswajit&password=educadora&nombre=Eitel&apellidos=Muncunil+Luque&email=fitzsimons.paovarat1%40carloshoya.com.ag&dni=00292664N&direccionA=C%2F+Felix+Rosso+158%2C+&ciudad=Venturada&cp=50687&provincia=Valladolid&ntc=0925167993472372&B1=Registrar http://localhost:8080/tienda1/miembros/editar.jsp HTTP/1.1

In [72]:
# Get probabilities for the test set
y_prob = model.predict_proba(X_test_tfidf)

# Probability of Anomalous class
anomalous_prob = y_prob[:, 1]

# Get the probabilities for the missed anomalous requests
missed_probabilities = anomalous_prob[missed]

print("Number of missed anomalous requests:", len(missed_probabilities))

print("\nAnomalous probability of first 20 missed requests:")
print(missed_probabilities[:20])

print("\nMinimum anomalous probability:",
      missed_probabilities.min())

print("Maximum anomalous probability:",
      missed_probabilities.max())

print("Average anomalous probability:",
      missed_probabilities.mean())

Number of missed anomalous requests: 285

Anomalous probability of first 20 missed requests:
[0.27394908 0.46498702 0.01749852 0.42501048 0.25447199 0.47416148
 0.00993254 0.00293507 0.03889346 0.22971939 0.37643532 0.3838906
 0.10988821 0.01217438 0.14082744 0.19802196 0.41377766 0.14183214
 0.01413545 0.2619945 ]

Minimum anomalous probability: 0.001483053258906348
Maximum anomalous probability: 0.49796735321328306
Average anomalous probability: 0.20165283040276016

In [73]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

thresholds = [0.50, 0.40, 0.30, 0.20]

for threshold in thresholds:

    y_pred_threshold = (anomalous_prob >= threshold).astype(int)

    accuracy = accuracy_score(y_test, y_pred_threshold)
    precision = precision_score(y_test, y_pred_threshold)
    recall = recall_score(y_test, y_pred_threshold)
    f1 = f1_score(y_test, y_pred_threshold)

    print(f"\nThreshold: {threshold}")
    print(f"Accuracy : {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall   : {recall * 100:.2f}%")
    print(f"F1-score : {f1 * 100:.2f}%")

Threshold: 0.5

Accuracy : 97.63%
Precision: 99.89%
Recall   : 94.31%
F1-score : 97.02%

Threshold: 0.4
Accuracy : 97.87%
Precision: 99.44%
Recall   : 95.35%
F1-score : 97.35%

Threshold: 0.3
Accuracy : 97.76%
Precision: 98.37%
Recall   : 96.13%
F1-score : 97.24%

Threshold: 0.2
Accuracy : 97.06%
Precision: 95.88%
Recall   : 97.01%
F1-score : 96.44%

In [74]:
y_pred_40 = (anomalous_prob >= 0.40).astype(int)

cm_40 = confusion_matrix(y_test, y_pred_40)

print("Confusion Matrix at threshold 0.40:")
print(cm_40)

Confusion Matrix at threshold 0.40:
[[7173   27]
 [ 233 4780]]

In [75]:
import joblib

joblib.dump(model, "logistic_regression_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model and TF-IDF vectorizer saved successfully.")

Model and TF-IDF vectorizer saved successfully.

In [76]:
import pandas as pd

csic_path = r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\dataset\csic_database.csv"

modern_path = r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\test_server\modern_normal_requests.csv"

csic_df = pd.read_csv(csic_path)
modern_df = pd.read_csv(modern_path)

print("CSIC:", csic_df.shape)
print("Modern normal:", modern_df.shape)

print("\nModern data:")
print(modern_df[["Method", "URL", "classification"]])

CSIC: (61065, 17)
Modern normal: (71, 8)

Modern data:
   Method                             URL  classification
0     GET          http://127.0.0.1:8000/               0
1     GET          http://127.0.0.1:8000/               0
2     GET          http://127.0.0.1:8000/               0
3     GET          http://127.0.0.1:8000/               0
4     GET          http://127.0.0.1:8000/               0
..    ...                             ...             ...
66   POST  http://127.0.0.1:8000/register               0
67   POST  http://127.0.0.1:8000/register               0
68   POST  http://127.0.0.1:8000/register               0
69   POST  http://127.0.0.1:8000/register               0
70   POST  http://127.0.0.1:8000/register               0

[71 rows x 3 columns]

In [77]:
modern_df = modern_df.drop_duplicates()

print("Modern rows after removing duplicates:", modern_df.shape[0])

print("\nUnique requests:")
print(modern_df[["Method", "URL", "classification"]])

Modern rows after removing duplicates: 63

Unique requests:
   Method                                    URL  classification
0     GET                 http://127.0.0.1:8000/               0
6     GET            http://127.0.0.1:8000/about               0
7     GET         http://127.0.0.1:8000/products               0
8     GET  http://127.0.0.1:8000/search?q=laptop               0
10    GET    http://127.0.0.1:8000/profile?id=10               0
..    ...                                    ...             ...
66   POST         http://127.0.0.1:8000/register               0
67   POST         http://127.0.0.1:8000/register               0
68   POST         http://127.0.0.1:8000/register               0
69   POST         http://127.0.0.1:8000/register               0
70   POST         http://127.0.0.1:8000/register               0

[63 rows x 3 columns]

In [78]:
import pandas as pd

modern_path = r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\test_server\modern_normal_requests.csv"

modern_df = pd.read_csv(modern_path)

print("Total rows:", len(modern_df))

modern_unique = modern_df.drop_duplicates()

print("Unique rows:", len(modern_unique))

print("\nMethods:")
print(modern_unique["Method"].value_counts())

print("\nClassification:")
print(modern_unique["classification"].value_counts())

Total rows: 71
Unique rows: 63

Methods:
Method
GET     50
POST    13
Name: count, dtype: int64

Classification:
classification
0    63
Name: count, dtype: int64

In [79]:
import pandas as pd

# Remove duplicates from modern data
modern_unique = modern_df.drop_duplicates().copy()

# Keep only the columns used by the model
text_columns = [
    "Method",
    "User-Agent",
    "host",
    "cookie",
    "content-type",
    "content",
    "URL"
]

# Prepare CSIC subset
csic_small = csic_df[
    text_columns + ["classification"]
].copy()

# Prepare modern subset
modern_small = modern_unique[
    text_columns + ["classification"]
].copy()

# Combine
combined_df = pd.concat(
    [csic_small, modern_small],
    ignore_index=True
)

# Build the same text format used by the model
combined_df["request_text"] = (
    combined_df[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

print("Combined shape:", combined_df.shape)

print("\nClass counts:")
print(combined_df["classification"].value_counts())

print("\nLast 5 modern examples:")
print(
    combined_df[
        ["Method", "URL", "classification", "request_text"]
    ].tail()
)

Combined shape: (61128, 9)

Class counts:
classification
0    36063
1    25065
Name: count, dtype: int64

Last 5 modern examples:
      Method                             URL  classification  \
61123   POST  http://127.0.0.1:8000/register               0
61124   POST  http://127.0.0.1:8000/register               0
61125   POST  http://127.0.0.1:8000/register               0
61126   POST  http://127.0.0.1:8000/register               0
61127   POST  http://127.0.0.1:8000/register               0

                                            request_text
61123  POST python-requests/2.34.2 127.0.0.1:8000  ap...
61124  POST python-requests/2.34.2 127.0.0.1:8000  ap...
61125  POST python-requests/2.34.2 127.0.0.1:8000  ap...
61126  POST python-requests/2.34.2 127.0.0.1:8000  ap...
61127  POST python-requests/2.34.2 127.0.0.1:8000  ap...

In [80]:
from sklearn.model_selection import train_test_split

X = combined_df["request_text"]
y = combined_df["classification"]

# First: 80% training, 20% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Split temporary data equally:
# 10% validation + 10% final test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Testing samples:", len(X_test))

print("\nTraining classes:")
print(y_train.value_counts())

print("\nValidation classes:")
print(y_val.value_counts())

print("\nTesting classes:")
print(y_test.value_counts())

Training samples: 48902
Validation samples: 6113
Testing samples: 6113

Training classes:
classification
0    28850
1    20052
Name: count, dtype: int64

Validation classes:
classification
0    3606
1    2507
Name: count, dtype: int64

Testing classes:
classification
0    3607
1    2506
Name: count, dtype: int64

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer

new_tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2)
)

X_train_tfidf = new_tfidf.fit_transform(X_train)

X_val_tfidf = new_tfidf.transform(X_val)
X_test_tfidf = new_tfidf.transform(X_test)

print("Training shape:", X_train_tfidf.shape)
print("Validation shape:", X_val_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)

Training shape: (48902, 50000)
Validation shape: (6113, 50000)
Testing shape: (6113, 50000)

In [82]:
from sklearn.linear_model import LogisticRegression

new_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

new_model.fit(X_train_tfidf, y_train)

print("New model trained successfully.")

New model trained successfully.

In [83]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Get anomaly probabilities for validation data
val_probabilities = new_model.predict_proba(X_val_tfidf)[:, 1]

thresholds = [0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20]

for threshold in thresholds:

    val_predictions = (
        val_probabilities >= threshold
    ).astype(int)

    accuracy = accuracy_score(y_val, val_predictions)
    precision = precision_score(y_val, val_predictions)
    recall = recall_score(y_val, val_predictions)
    f1 = f1_score(y_val, val_predictions)

    print(f"\nThreshold {threshold:.2f}")
    print(f"Accuracy : {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall   : {recall * 100:.2f}%")
    print(f"F1-score : {f1 * 100:.2f}%")

Threshold 0.50
Accuracy : 97.56%
Precision: 99.75%
Recall   : 94.30%
F1-score : 96.94%

Threshold 0.45
Accuracy : 97.69%
Precision: 99.50%
Recall   : 94.85%
F1-score : 97.12%

Threshold 0.40
Accuracy : 97.76%
Precision: 99.05%
Recall   : 95.45%
F1-score : 97.22%

Threshold 0.35
Accuracy : 97.78%
Precision: 98.57%
Recall   : 95.97%
F1-score : 97.25%

Threshold 0.30
Accuracy : 97.45%
Precision: 97.53%
Recall   : 96.21%
F1-score : 96.87%

Threshold 0.25
Accuracy : 97.14%
Precision: 96.53%
Recall   : 96.49%
F1-score : 96.51%

Threshold 0.20
Accuracy : 96.65%
Precision: 94.93%
Recall   : 97.01%
F1-score : 95.96%

In [84]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

threshold = 0.35

test_probabilities = new_model.predict_proba(X_test_tfidf)[:, 1]

test_predictions = (
    test_probabilities >= threshold
).astype(int)

print("FINAL TEST RESULTS")
print("------------------")

print(
    "Accuracy:",
    round(accuracy_score(y_test, test_predictions) * 100, 2),
    "%"
)

print(
    "Precision:",
    round(precision_score(y_test, test_predictions) * 100, 2),
    "%"
)

print(
    "Recall:",
    round(recall_score(y_test, test_predictions) * 100, 2),
    "%"
)

print(
    "F1-score:",
    round(f1_score(y_test, test_predictions) * 100, 2),
    "%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        test_predictions,
        target_names=["Normal", "Anomalous"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, test_predictions))

FINAL TEST RESULTS
------------------
Accuracy: 97.86 %
Precision: 99.05 %
Recall: 95.69 %
F1-score: 97.34 %

Classification Report:
              precision    recall  f1-score   support

      Normal       0.97      0.99      0.98      3607
   Anomalous       0.99      0.96      0.97      2506

    accuracy                           0.98      6113
   macro avg       0.98      0.98      0.98      6113
weighted avg       0.98      0.98      0.98      6113

Confusion Matrix:
[[3584   23]
 [ 108 2398]]

In [85]:
# Build request_text for the modern normal dataset

modern_test = modern_unique.copy()

modern_test["request_text"] = (
    modern_test[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

# Transform using the NEW vectorizer
modern_X = new_tfidf.transform(
    modern_test["request_text"]
)

# Get anomaly probabilities
modern_probabilities = new_model.predict_proba(modern_X)[:, 1]

# Use our selected threshold
modern_predictions = (
    modern_probabilities >= 0.35
).astype(int)

modern_test["anomaly_probability"] = modern_probabilities
modern_test["prediction"] = modern_predictions

print("Total modern requests:", len(modern_test))

print(
    "Predicted Normal:",
    (modern_predictions == 0).sum()
)

print(
    "Predicted Anomalous:",
    (modern_predictions == 1).sum()
)

print(
    "\nModern Normal Accuracy:",
    round((modern_predictions == 0).mean() * 100, 2),
    "%"
)

print("\nResults:")
print(
    modern_test[
        ["Method", "URL", "anomaly_probability", "prediction"]
    ]
)

Total modern requests: 63
Predicted Normal: 52
Predicted Anomalous: 11

Modern Normal Accuracy: 82.54 %

Results:
   Method                                    URL  anomaly_probability  \
0     GET                 http://127.0.0.1:8000/             0.875763
6     GET            http://127.0.0.1:8000/about             0.882424
7     GET         http://127.0.0.1:8000/products             0.875763
8     GET  http://127.0.0.1:8000/search?q=laptop             0.862144
10    GET    http://127.0.0.1:8000/profile?id=10             0.823815
..    ...                                    ...                  ...
66   POST         http://127.0.0.1:8000/register             0.503303
67   POST         http://127.0.0.1:8000/register             0.377522
68   POST         http://127.0.0.1:8000/register             0.501762
69   POST         http://127.0.0.1:8000/register             0.480504
70   POST         http://127.0.0.1:8000/register             0.485763

    prediction
0            1
6            1
7            1
8            1
10           1
..         ...
66           1
67           1
68           1
69           1
70           1

[63 rows x 4 columns]

In [86]:
import pandas as pd

large_path = r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\test_server\modern_normal_large.csv"

large_modern = pd.read_csv(large_path)

print("Total rows:", len(large_modern))

large_unique = large_modern.drop_duplicates()

print("Unique rows:", len(large_unique))

print("\nMethods:")
print(large_unique["Method"].value_counts())

print("\nClasses:")
print(large_unique["classification"].value_counts())

print("\nSample:")
print(
    large_unique[
        ["Method", "User-Agent", "URL", "classification"]
    ].head(10)
)

Total rows: 999
Unique rows: 488

Methods:
Method
GET     288
POST    200
Name: count, dtype: int64

Classes:
classification
0    488
Name: count, dtype: int64

Sample:
  Method                                         User-Agent  \
0    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
1    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
2    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
3    GET  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
4    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
5    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
6    GET  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
7    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
8    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
9    GET  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...

                                                URL  classification
0    http://127.0.0.1:8000/page/terms?ref=0&lang=en               0
1     http://127.0.0.1:8000/page/blog?ref=1&lang=en               0
2     http://127.0.0.1:8000/page/help?ref=2&lang=en               0
3    http://127.0.0.1:8000/page/terms?ref=3&lang=en               0
4  http://127.0.0.1:8000/page/privacy?ref=4&lang=en               0
5     http://127.0.0.1:8000/page/home?ref=5&lang=en               0
6     http://127.0.0.1:8000/page/help?ref=6&lang=en               0
7   http://127.0.0.1:8000/page/faq?ref=7&lang=en-IN               0
8  http://127.0.0.1:8000/page/help?ref=8&lang=en-IN               0
9  http://127.0.0.1:8000/page/account?ref=9&lang=en               0

In [87]:
from sklearn.model_selection import train_test_split

large_unique = large_unique.copy()

modern_train, modern_test = train_test_split(
    large_unique,
    test_size=0.20,
    random_state=42
)

print("Modern training requests:", len(modern_train))
print("Modern unseen test requests:", len(modern_test))

print("\nTraining methods:")
print(modern_train["Method"].value_counts())

print("\nUnseen test methods:")
print(modern_test["Method"].value_counts())

Modern training requests: 390
Modern unseen test requests: 98

Training methods:
Method
GET     231
POST    159
Name: count, dtype: int64

Unseen test methods:
Method
GET     57
POST    41
Name: count, dtype: int64

In [88]:
import pandas as pd
from sklearn.model_selection import train_test_split

text_columns = [
    "Method",
    "User-Agent",
    "host",
    "cookie",
    "content-type",
    "content",
    "URL"
]

# Prepare original CSIC data
csic_final = csic_df[
    text_columns + ["classification"]
].copy()

# Prepare ONLY modern training data
modern_train_final = modern_train[
    text_columns + ["classification"]
].copy()

# Combine CSIC + modern training requests
final_df = pd.concat(
    [csic_final, modern_train_final],
    ignore_index=True
)

# Construct request text
final_df["request_text"] = (
    final_df[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

print("Combined training pool:", len(final_df))

print("\nClass counts:")
print(final_df["classification"].value_counts())

Combined training pool: 61455

Class counts:
classification
0    36390
1    25065
Name: count, dtype: int64

In [89]:
X = final_df["request_text"]
y = final_df["classification"]

# 80% train, 20% temporary
X_train_final, X_temp_final, y_train_final, y_temp_final = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Temporary 20% -> 10% validation + 10% test
X_val_final, X_test_final, y_val_final, y_test_final = train_test_split(
    X_temp_final,
    y_temp_final,
    test_size=0.50,
    random_state=42,
    stratify=y_temp_final
)

print("Training:", len(X_train_final))
print("Validation:", len(X_val_final))
print("Testing:", len(X_test_final))

Training: 49164
Validation: 6145
Testing: 6146

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer

final_tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2)
)

X_train_final_tfidf = final_tfidf.fit_transform(X_train_final)

X_val_final_tfidf = final_tfidf.transform(X_val_final)
X_test_final_tfidf = final_tfidf.transform(X_test_final)

print("Train:", X_train_final_tfidf.shape)
print("Validation:", X_val_final_tfidf.shape)
print("Test:", X_test_final_tfidf.shape)

Train: (49164, 50000)
Validation: (6145, 50000)
Test: (6146, 50000)

In [91]:
from sklearn.linear_model import LogisticRegression

final_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

final_model.fit(
    X_train_final_tfidf,
    y_train_final
)

print("Final model trained successfully.")

Final model trained successfully.

In [92]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

val_probabilities = final_model.predict_proba(
    X_val_final_tfidf
)[:, 1]

thresholds = [
    0.50,
    0.45,
    0.40,
    0.35,
    0.30,
    0.25,
    0.20
]

for threshold in thresholds:

    predictions = (
        val_probabilities >= threshold
    ).astype(int)

    accuracy = accuracy_score(
        y_val_final, predictions
    )

    precision = precision_score(
        y_val_final, predictions
    )

    recall = recall_score(
        y_val_final, predictions
    )

    f1 = f1_score(
        y_val_final, predictions
    )

    print(f"\nThreshold {threshold:.2f}")

    print(
        f"Accuracy : {accuracy * 100:.2f}%"
    )

    print(
        f"Precision: {precision * 100:.2f}%"
    )

    print(
        f"Recall   : {recall * 100:.2f}%"
    )

    print(
        f"F1-score : {f1 * 100:.2f}%"
    )

Threshold 0.50
Accuracy : 97.67%
Precision: 99.92%
Recall   : 94.37%
F1-score : 97.07%

Threshold 0.45
Accuracy : 97.79%
Precision: 99.75%
Recall   : 94.81%
F1-score : 97.22%

Threshold 0.40
Accuracy : 97.92%
Precision: 99.62%
Recall   : 95.25%
F1-score : 97.39%

Threshold 0.35
Accuracy : 97.97%
Precision: 99.38%
Recall   : 95.61%
F1-score : 97.46%

Threshold 0.30
Accuracy : 97.85%
Precision: 98.53%
Recall   : 96.17%
F1-score : 97.33%

Threshold 0.25
Accuracy : 97.58%
Precision: 97.31%
Recall   : 96.73%
F1-score : 97.02%

Threshold 0.20
Accuracy : 97.12%
Precision: 95.72%
Recall   : 97.29%
F1-score : 96.50%

In [93]:
# Prepare the 98 completely unseen modern normal requests

modern_test = modern_test.copy()

modern_test["request_text"] = (
    modern_test[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

modern_test_tfidf = final_tfidf.transform(
    modern_test["request_text"]
)

modern_test_probabilities = final_model.predict_proba(
    modern_test_tfidf
)[:, 1]

threshold = 0.35

modern_test_predictions = (
    modern_test_probabilities >= threshold
).astype(int)

normal_count = (modern_test_predictions == 0).sum()
anomalous_count = (modern_test_predictions == 1).sum()

modern_accuracy = (
    modern_test_predictions == 0
).mean()

print("UNSEEN MODERN NORMAL TEST")
print("-------------------------")

print("Total requests:", len(modern_test))
print("Predicted Normal:", normal_count)
print("Predicted Anomalous:", anomalous_count)

print(
    "Modern Normal Accuracy:",
    round(modern_accuracy * 100, 2),
    "%"
)

UNSEEN MODERN NORMAL TEST
-------------------------
Total requests: 98
Predicted Normal: 98
Predicted Anomalous: 0
Modern Normal Accuracy: 100.0 %

In [94]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

test_probabilities = final_model.predict_proba(
    X_test_final_tfidf
)[:, 1]

threshold = 0.35

test_predictions = (
    test_probabilities >= threshold
).astype(int)

print("FINAL STANDARD TEST RESULTS")
print("---------------------------")

print(
    "Accuracy:",
    round(
        accuracy_score(
            y_test_final,
            test_predictions
        ) * 100,
        2
    ),
    "%"
)

print(
    "Precision:",
    round(
        precision_score(
            y_test_final,
            test_predictions
        ) * 100,
        2
    ),
    "%"
)

print(
    "Recall:",
    round(
        recall_score(
            y_test_final,
            test_predictions
        ) * 100,
        2
    ),
    "%"
)

print(
    "F1-score:",
    round(
        f1_score(
            y_test_final,
            test_predictions
        ) * 100,
        2
    ),
    "%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_test_final,
        test_predictions,
        target_names=["Normal", "Anomalous"]
    )
)

print("Confusion Matrix:")
print(
    confusion_matrix(
        y_test_final,
        test_predictions
    )
)

FINAL STANDARD TEST RESULTS
---------------------------
Accuracy: 97.93 %
Precision: 99.13 %
Recall: 95.77 %
F1-score: 97.42 %

Classification Report:
              precision    recall  f1-score   support

      Normal       0.97      0.99      0.98      3639
   Anomalous       0.99      0.96      0.97      2507

    accuracy                           0.98      6146
   macro avg       0.98      0.98      0.98      6146
weighted avg       0.98      0.98      0.98      6146

Confusion Matrix:
[[3618   21]
 [ 106 2401]]

In [95]:
import joblib

joblib.dump(
    final_model,
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\model\logistic_regression_model_final.pkl"
)

joblib.dump(
    final_tfidf,
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\model\tfidf_vectorizer_final.pkl"
)

print("Final model and vectorizer saved successfully.")

Final model and vectorizer saved successfully.

In [96]:
# Get one real anomalous request from CSIC dataset

attack = csic_df[
    csic_df["classification"] == 1
].iloc[0]

for column in text_columns:
    print(column, ":", attack[column])

Method : GET
User-Agent : Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)
host : localhost:8080
cookie : JSESSIONID=B92A8B48B9008CD29F622A994E0F650D
content-type : nan
content : nan
URL : http://localhost:8080/tienda1/publico/anadir.jsp?id=2&nombre=Jam%F3n+Ib%E9rico&precio=85&cantidad=%27%3B+DROP+TABLE+usuarios%3B+SELECT+*+FROM+datos+WHERE+nombre+LIKE+%27%25&B1=A%F1adir+al+carrito HTTP/1.1

In [97]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\dataset\csic_database.csv"
)

columns = [
    "Method", "User-Agent", "host", "cookie",
    "content-type", "content", "URL"
]

# Use only anomalous CSIC requests
anomalous = df[df["classification"] == 1].copy()

anomalous["request_text"] = (
    anomalous[columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

# Use the final model already loaded in the notebook
X_anomalous = final_tfidf.transform(anomalous["request_text"])

anomalous["score"] = (
    final_model.predict_proba(X_anomalous)[:, 1] * 100
)

# Find URLs above 60% that do not contain our obvious rule patterns
patterns = [
    "' or ", '" or ', "drop table", "union select",
    "<script", "javascript:", "../", "%3cscript", "%27%3b"
]

candidates = anomalous[
    (anomalous["score"] >= 60) &
    (~anomalous["URL"].fillna("").str.lower().apply(
        lambda x: any(p in x for p in patterns)
    ))
]

print("Candidates found:", len(candidates))

if len(candidates) > 0:
    row = candidates.iloc[0]
    print("\nScore:", round(row["score"], 2), "%")
    print("URL:")
    print(row["URL"])

Candidates found: 23232

Score: 97.21 %
URL:
http://localhost:8080/tienda1/publico/anadir.jsp HTTP/1.1

In [98]:
clean_candidates = candidates[
    ~candidates["URL"].fillna("").str.contains(
        "HTTP/1.1",
        case=False,
        regex=False
    )
]

print("Clean candidates:", len(clean_candidates))

if len(clean_candidates) > 0:
    row = clean_candidates.iloc[0]
    print("Score:", round(row["score"], 2), "%")
    print("URL:", row["URL"])

Clean candidates: 0

In [99]:
row = candidates.iloc[0]

clean_url = str(row["URL"]).replace(" HTTP/1.1", "").strip()

print("Original ML score:", round(row["score"], 2), "%")
print("Clean URL:")
print(clean_url)

Original ML score: 97.21 %
Clean URL:
http://localhost:8080/tienda1/publico/anadir.jsp

In [100]:
import pandas as pd

test_urls = [
    # Normal URLs
    ["https://www.google.com", 0],
    ["https://www.youtube.com", 0],
    ["https://www.wikipedia.org", 0],
    ["https://github.com", 0],
    ["https://www.google.com/search?q=python", 0],
    ["https://en.wikipedia.org/wiki/Machine_learning", 0],
    ["https://github.com/topics/python", 0],
    ["https://example.com/products?id=10", 0],
    ["https://example.com/search?q=laptop", 0],
    ["https://example.com/profile?user=alex", 0],

    # Suspicious test URLs
    ["http://example.com/search?q=<script>alert('test')</script>", 1],
    ["http://example.com/login?username=admin' OR '1'='1", 1],
    ["http://example.com/page?file=../../etc/passwd", 1],
    ["http://example.com/search?q=UNION SELECT username,password", 1],
    ["http://example.com/page?next=javascript:alert('test')", 1]
]

gateway_test = pd.DataFrame(
    test_urls,
    columns=["URL", "Expected"]
)

gateway_test.to_csv(
    r"C:\Users\USER\OneDrive\Documents\AI_Web_Security\test_server\gateway_test_urls.csv",
    index=False
)

print(gateway_test)
print("\nTotal:", len(gateway_test))

                                                  URL  Expected
0                              https://www.google.com         0
1                             https://www.youtube.com         0
2                           https://www.wikipedia.org         0
3                                  https://github.com         0
4              https://www.google.com/search?q=python         0
5      https://en.wikipedia.org/wiki/Machine_learning         0
6                    https://github.com/topics/python         0
7                  https://example.com/products?id=10         0
8                 https://example.com/search?q=laptop         0
9               https://example.com/profile?user=alex         0
10  http://example.com/search?q=<script>alert('tes...         1
11  http://example.com/login?username=admin' OR '1...         1
12      http://example.com/page?file=../../etc/passwd         1
13  http://example.com/search?q=UNION SELECT usern...         1
14  http://example.com/page?next=javascript:alert(...         1

Total: 15

In [101]:
import requests

results = []

for _, row in gateway_test.iterrows():

    url = row["URL"]

    data = {
        "Method": "GET",
        "User-Agent": "Mozilla/5.0",
        "host": "",
        "cookie": "",
        "content-type": "",
        "content": "",
        "URL": url
    }

    response = requests.post(
        "http://127.0.0.1:5000/predict",
        json=data
    ).json()

    score = response["anomalous_probability"] * 100

    # Same pattern rules used by gateway
    url_lower = url.lower()

    patterns = [
        "' or ",
        "\" or ",
        "drop table",
        "union select",
        "<script",
        "javascript:",
        "../",
        "%3cscript",
        "%27%3b"
    ]

    detected = [
        pattern for pattern in patterns
        if pattern in url_lower
    ]

    results.append([
        url,
        row["Expected"],
        round(score, 2),
        ", ".join(detected) if detected else "None"
    ])

gateway_results = pd.DataFrame(
    results,
    columns=[
        "URL",
        "Expected",
        "ML_Score",
        "Pattern_Detected"
    ]
)

print(gateway_results.to_string(index=False))

                                                       URL  Expected  ML_Score Pattern_Detected
                                    https://www.google.com         0     99.91             None
                                   https://www.youtube.com         0     99.73             None
                                 https://www.wikipedia.org         0     99.91             None
                                        https://github.com         0     99.76             None
                    https://www.google.com/search?q=python         0     99.93             None
            https://en.wikipedia.org/wiki/Machine_learning         0     99.94             None
                          https://github.com/topics/python         0     99.93             None
                        https://example.com/products?id=10         0     99.49             None
                       https://example.com/search?q=laptop         0     99.90             None
                     https://example.com/profile?user=alex         0     99.94             None
http://example.com/search?q=<script>alert('test')</script>         1     99.91          <script
        http://example.com/login?username=admin' OR '1'='1         1     99.86            ' or
             http://example.com/page?file=../../etc/passwd         1     99.89              ../
http://example.com/search?q=UNION SELECT username,password         1     99.75     union select
     http://example.com/page?next=javascript:alert('test')         1     99.89      javascript:

In [102]:
import requests
import pandas as pd

results = []

for _, row in gateway_test.iterrows():

    url = row["URL"]

    data = {
        "Method": "GET",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36 Edg/152.0.0.0",
        "host": "",
        "cookie": "",
        "content-type": "",
        "content": "",
        "URL": url
    }

    response = requests.post(
        "http://127.0.0.1:5000/predict",
        json=data
    ).json()

    score = response["anomalous_probability"] * 100

    patterns = [
        "' or ",
        "\" or ",
        "drop table",
        "union select",
        "<script",
        "javascript:",
        "../",
        "%3cscript",
        "%27%3b"
    ]

    detected = [
        pattern for pattern in patterns
        if pattern in url.lower()
    ]

    results.append([
        url,
        row["Expected"],
        round(score, 2),
        ", ".join(detected) if detected else "None"
    ])

gateway_results = pd.DataFrame(
    results,
    columns=["URL", "Expected", "ML_Score", "Pattern_Detected"]
)

print(gateway_results.to_string(index=False))

                                                       URL  Expected  ML_Score Pattern_Detected
                                    https://www.google.com         0     18.74             None
                                   https://www.youtube.com         0     15.32             None
                                 https://www.wikipedia.org         0     17.51             None
                                        https://github.com         0     15.64             None
                    https://www.google.com/search?q=python         0     28.81             None
            https://en.wikipedia.org/wiki/Machine_learning         0     19.69             None
                          https://github.com/topics/python         0     19.89             None
                        https://example.com/products?id=10         0     14.77             None
                       https://example.com/search?q=laptop         0     19.56             None
                     https://example.com/profile?user=alex         0     25.32             None
http://example.com/search?q=<script>alert('test')</script>         1     22.70          <script
        http://example.com/login?username=admin' OR '1'='1         1     21.51            ' or
             http://example.com/page?file=../../etc/passwd         1     20.13              ../
http://example.com/search?q=UNION SELECT username,password         1     16.44     union select
     http://example.com/page?next=javascript:alert('test')         1     21.45      javascript:

In [103]:
import requests
import pandas as pd

results = []

for _, row in gateway_test.iterrows():

    url = row["URL"]

    data = {
        "Method": "GET",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36 Edg/153.0.0.0",
        "host": "",
        "cookie": "",
        "content-type": "",
        "content": "",
        "URL": url
    }

    response = requests.post(
        "http://127.0.0.1:5000/predict",
        json=data
    ).json()

    score = response["anomalous_probability"] * 100

    patterns = [
        "' or ",
        "\" or ",
        "drop table",
        "union select",
        "<script",
        "javascript:",
        "../",
        "%3cscript",
        "%27%3b"
    ]

    detected = [
        pattern for pattern in patterns
        if pattern in url.lower()
    ]

    results.append([
        url,
        row["Expected"],
        round(score, 2),
        ", ".join(detected) if detected else "None"
    ])

gateway_results = pd.DataFrame(
    results,
    columns=["URL", "Expected", "ML_Score", "Pattern_Detected"]
)

print(gateway_results.to_string(index=False))

                                                       URL  Expected  ML_Score Pattern_Detected
                                    https://www.google.com         0     48.15             None
                                   https://www.youtube.com         0     43.25             None
                                 https://www.wikipedia.org         0     47.07             None
                                        https://github.com         0     43.91             None
                    https://www.google.com/search?q=python         0     59.54             None
            https://en.wikipedia.org/wiki/Machine_learning         0     49.99             None
                          https://github.com/topics/python         0     50.01             None
                        https://example.com/products?id=10         0     40.23             None
                       https://example.com/search?q=laptop         0     48.99             None
                     https://example.com/profile?user=alex         0     56.18             None
http://example.com/search?q=<script>alert('test')</script>         1     52.66          <script
        http://example.com/login?username=admin' OR '1'='1         1     50.40            ' or
             http://example.com/page?file=../../etc/passwd         1     49.47              ../
http://example.com/search?q=UNION SELECT username,password         1     42.84     union select
     http://example.com/page?next=javascript:alert('test')         1     50.93      javascript: